### ISSUE TITLE
 Trying to connect two Dualshocks via ds4drv, but only one is detected

### ISSUE THREAD

**Issue by ee5cd7d5d** [TheDrHax/ds4drv-cemuhook#16]
What's the problem? Describe what went wrong.

I tried connecting two DualsShocks 4 via DSU Client to the Dolphin emulator as described here: https://wiki.dolphin-emu.org/index.php?title=DSU_Client but only one is recognized (DSUClient/0/xxx, DSUClient/1/xxx is missing). I tried testing with the DSU Pad Test application over wine, same thing only one DS4 is recognized.

What steps will reproduce the problem?

Connect two DS4 via Bluetooth, open devices configuration on Dolphin, add DSU source.

What is the system information?

```
                   -`                    pedro@arctic 
                  .o+`                   ------------ 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: Skylake Platform 0.1 
               `+oooooo:                 Kernel: 5.11.13-arch1-1 
               -+oooooo+:                Uptime: 9 hours, 41 mins 
             `/:-:++oooo+:               Packages: 1692 (pacman) 
            `/++++/+++++++:              Shell: zsh 5.8 
           `/++++++++++++++:             Resolution: 1920x1080 
          `/+++ooooooooooooo/`           DE: Plasma 5.21.4 
         ./ooosssso++osssssso+`          WM: KWin 
        .oossssso-````/ossssss+`         WM Theme: ChromeOS-dark 
       -osssssso.      :ssssssso.        Theme: ChromeOSDark [Plasma], Breeze [GTK3] 
      :osssssss/        osssso+++.       Icons: Tela-dark [Plasma], Tela-dark [GTK2/3] 
     /ossssssss/        +ssssooo/-       Terminal: yakuake 
   `/ossssso+/:-        -:/+osssso+-     CPU: Intel i7-6500U (4) @ 3.100GHz 
  `+sso+:-`                 `.-/+oso:    GPU: Intel Skylake GT2 [HD Graphics 520] 
 `++:.                           `-/+/   Memory: 3087MiB / 7868MiB 
 .`                                 `/
```

Dolphin Version: 5.0-14002

Tested with ds4drv 0.5.1

**Comment by TheDrHax** [comment]
Current implementation of UDP server only supports [one controller at a time](https://github.com/TheDrHax/ds4drv-cemuhook/blob/master/ds4drv/servers/udp.py#L69). The driver, in theory, does support [multiple controllers](https://github.com/chrippa/ds4drv#multiple-controllers), but I do not have the second one to test this.

**Comment by ee5cd7d5d** [comment]
I could actually try to implement it myself when I have time :) could you give me a rough idea of what I would need to do in order to achieve that? Like how would I need to change the UDP packet...

**Comment by TheDrHax** [comment]
1. Right now UDP server is being started inside controller's thread, so when there are two controllers, there will be two servers. We probably need to initialize a single UDP server instance before any controllers are registered in `__main__.py` instead of doing it in `input.py`;

https://github.com/TheDrHax/ds4drv-cemuhook/blob/28aa88cc8b3599227d95a3fb89c0df12a0e08fd6/ds4drv/actions/input.py#L100-L104

https://github.com/TheDrHax/ds4drv-cemuhook/blob/28aa88cc8b3599227d95a3fb89c0df12a0e08fd6/ds4drv/__main__.py#L176-L178

2. For client to be able to detect multiple controllers, we need to send multiple packets from `UDPServer._req_ports`. This part is almost ready, we just need to keep count of active controllers and populate responses with real data (MAC address);

https://github.com/TheDrHax/ds4drv-cemuhook/blob/28aa88cc8b3599227d95a3fb89c0df12a0e08fd6/ds4drv/servers/udp.py#L64-L72

3. In `UDPServer.report` "pad id" field will depend on the source of the report. Right now it is hard coded to 0 (first controller);

https://github.com/TheDrHax/ds4drv-cemuhook/blob/28aa88cc8b3599227d95a3fb89c0df12a0e08fd6/ds4drv/servers/udp.py#L109-L115

4. To read input events from each controller we can probably use `DS4Controller.loop.register_event("device-report", callback)` instead of modifying `ReportActionInput.handle_report`.

https://github.com/TheDrHax/ds4drv-cemuhook/blob/28aa88cc8b3599227d95a3fb89c0df12a0e08fd6/ds4drv/actions/input.py#L133-L135

I will try to make it work with a single controller. Probably it will then start working with multiple controllers as well :)

**Comment by TheDrHax** [comment]
I've created a separate branch for this feature. Could you please test it?

* `pip3 install git+https://github.com/TheDrHax/ds4drv-cemuhook.git@multiple-controllers`
* `ds4drv --hidraw --udp --next-controller`

**Comment by ee5cd7d5d** [comment]
Hi! It's working better now, at least there is data from both controllers, but it seems to be mixing up the packets. Now Dolphin is detecting both controllers but it's showing the sensors from both in both, switching very rapidly between the values of each controller (like several times per second)

**Comment by TheDrHax** [comment]
I was able to reproduce this issue with a single controller by copying reports to another slot and changing them slightly.

Apparently, Dolphin creates a separate connection for each controller, ignores `pad id` byte and expects only updates for a single controller per connection. So the server needs to keep track of each client's requests.

**Comment by TheDrHax** [comment]
Oh, this TODO is exactly what we need:

https://github.com/TheDrHax/ds4drv-cemuhook/blob/28aa88cc8b3599227d95a3fb89c0df12a0e08fd6/ds4drv/servers/udp.py#L74-L81

The protocol supports two different modes for data transfer: [slot-based and MAC-based](https://v1993.github.io/cemuhook-protocol/#incoming-packet-structure-2).

**Comment by ee5cd7d5d** [comment]
I checked with a newer build of dolphin to see if it improved, but the problem remains. I will not get to look into it right away, but let me know if I can do anything to help 😊

**Comment by TheDrHax** [comment]
I pushed another change to the same branch. It works with Dolphin now (at least on my side) :)

**Comment by ee5cd7d5d** [comment]
Yes! It works! Thank you so much!

**Comment by TheDrHax** [comment]
Nice! I will merge it with master now :+1:

**Comment by oblitum** [comment]
This seems to not have fixed on cemu's side.. I can only get one game pad motion source (DSU1) listed in options, all others show as disconnected, despite the ds4drv logs showing two controllers got connected.
